# Default values for Ruby.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1
image:
  repository: pipo02mix/onodo
  tag: 0.0.1
  pullPolicy: IfNotPresent
service:
  name: onodo
  type: ClusterIP
  externalPort: 80
  internalPort: 3080
  externalPort2: 3080
  internalPort2: 3080
resources:
  limits:
    cpu: 100m
    memory: 2Gi
  requests:
    cpu: 100m
    memory: 2Gi
ingress:
  enabled: false
