apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: db
  labels:
    app: db
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: db
    spec:
      containers:
      - name: db
        image: pipo02mix/postgres:0.0.1
        ports:
        - containerPort: 5432
