apiVersion: v1
kind: Service
metadata:
  name: postgres
  labels:
    app: db
spec:
  type: ClusterIP
  ports:
  - port: 5432
    targetPort: 5432
    protocol: TCP
    name: db
  selector:
    app: db
